apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itorchestra-service.fullname" . }}
  labels:
    {{- include "itorchestra-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "itorchestra-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "itorchestra-service.selectorLabels" . | nindent 8 }}
      {{- if or .Values.linkerd.inject .Values.podAnnotations }}
      annotations:
        {{- if .Values.linkerd.inject }}
        linkerd.io/inject: enabled
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "itorchestra-service.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "itorchestra-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if eq .Values.probes.type "grpc" }}
          readinessProbe:
            grpc: { port: {{ .Values.containerPort }} }
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          livenessProbe:
            grpc: { port: {{ .Values.containerPort }} }
            initialDelaySeconds: {{ add .Values.probes.initialDelaySeconds 20 }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          {{- else if eq .Values.probes.type "http" }}
          readinessProbe:
            httpGet: { path: {{ .Values.probes.path }}, port: {{ .Values.containerPort }} }
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          livenessProbe:
            httpGet: { path: {{ .Values.probes.path }}, port: {{ .Values.containerPort }} }
            initialDelaySeconds: {{ add .Values.probes.initialDelaySeconds 20 }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
